[package]
name = "feup-thesis-rt-drl"
version = "0.1.0"
edition = "2021"

[dependencies]
ctor = "0.2.8"
gnuplot = "0.0.43"
memory-stats = "1.1.0"
rand = "0.8.5"
serde = "1.0.203"
tch = {version = "0.10.0"}
statrs = "0.17.1"
threadpool = "1.8.1"